config/routes.rb
Rails.application.routes.draw do
  resources :imports, :only => [:index, :new, :create]
  get 'imports/success' => 'imports#success', as: :success
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import.rb
class Import
  include ActiveModel::Model
  attr_accessor :name
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imports_controller.rb
require 'typhoeus'
require 'json'
require 'csv'


class ImportsController < ApplicationController
  #before_action :set_import, only: [:show, :edit, :update, :destroy]

  # GET /imports
  # GET /imports.json
  def index
  end

  # GET /imports/1
  # GET /imports/1.json
  def show
  end

  # GET /imports/new
  def new
    @import = Import.new
  end

  # GET /imports/1/edit
  def edit
  end

  # POST /imports
  # POST /imports.json
  def create
    
    canvas_url = ''
    canvas_token = ''
    
    @import = Import.new(import_params)

    if @import.valid?
      find_user = Typhoeus::Request.new(
        "#{canvas_url}/api/v1/accounts/self/users",
        method: :get,
        headers: { authorization: "Bearer #{canvas_token}"},
        params: {
          "search_term" => @import.name
        }
        )  
  
        find_user.on_complete do |response|
          if response.code == 200
            redirect_to @import, notice: JSON.parse(response.body)
          else
            render html: response.code #@import.errors, status: :unprocessable_entity
          end
            #We use '.first' simply because the array only has a length of 1 (ie. The search should only return one user, hopefully.)
          end        
        end
      find_user.run #Find me that user and get that SIS ID.    
    
  end
  # PATCH/PUT /imports/1
  # PATCH/PUT /imports/1.json
  def update
    respond_to do |format|
      if @import.update(import_params)
        format.html { redirect_to @import, notice: 'Import was successfully updated.' }
        format.json { render :show, status: :ok, location: @import }
      else
        format.html { render :edit }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imports/1
  # DELETE /imports/1.json
  def destroy
    @import.destroy
    respond_to do |format|
      format.html { redirect_to imports_url, notice: 'Import was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  #  def set_import
  #    @import = Import.find(params[:id])
  #  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def import_params
      params.require(:import).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/_form.html.erb
 <%= form_for(@import) do |f| %>
 <% if @import.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@import.errors.count, "error") %> prohibited this feedback from being saved:</h2>
     <ul>
     <% @import.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>
 
 <br>
 <div class="field">
   <%= f.label :name %><br>
   <%= f.text_field :name %>
 </div>

 
 <div class="actions">
   <%= f.submit "Search"%>
 </div>
 
<% end %>
 

app/views/imports/edit.html.erb
<h1>Editing Import</h1>

<%= render 'form', import: @import %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

app/views/imports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Search for a User</h1>


<br>

<%= link_to 'New Search', new_import_path %>

app/views/imports/new.html.erb
<h1>New Search Query</h1>

<%= render 'form', import: @import %>

<%= link_to 'Back', imports_path %>

app/views/imports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_import_path(@import) %> |
<%= link_to 'Back', imports_path %>

app/views/imports/success.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_import_path(@import) %> |
<%= link_to 'Back', imports_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tools</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>